# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/burnt/Github/Osodio

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/burnt/Github/Osodio

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/burnt/Github/Osodio/CMakeFiles /home/burnt/Github/Osodio//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/burnt/Github/Osodio/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named llhttp

# Build rule for target.
llhttp: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 llhttp
.PHONY : llhttp

# fast build rule for target.
llhttp/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/llhttp.dir/build.make CMakeFiles/llhttp.dir/build
.PHONY : llhttp/fast

#=============================================================================
# Target rules for targets named simdjson

# Build rule for target.
simdjson: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 simdjson
.PHONY : simdjson

# fast build rule for target.
simdjson/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/simdjson.dir/build.make CMakeFiles/simdjson.dir/build
.PHONY : simdjson/fast

#=============================================================================
# Target rules for targets named osodio

# Build rule for target.
osodio: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 osodio
.PHONY : osodio

# fast build rule for target.
osodio/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/osodio.dir/build.make CMakeFiles/osodio.dir/build
.PHONY : osodio/fast

#=============================================================================
# Target rules for targets named example

# Build rule for target.
example: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 example
.PHONY : example

# fast build rule for target.
example/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/example.dir/build.make CMakeFiles/example.dir/build
.PHONY : example/fast

#=============================================================================
# Target rules for targets named distclean

# Build rule for target.
distclean: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 distclean
.PHONY : distclean

# fast build rule for target.
distclean/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/distclean.dir/build.make CMakeFiles/distclean.dir/build
.PHONY : distclean/fast

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/example.dir/build.make CMakeFiles/example.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/example.dir/build.make CMakeFiles/example.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/example.dir/build.make CMakeFiles/example.dir/main.cpp.s
.PHONY : main.cpp.s

src/app.o: src/app.cpp.o
.PHONY : src/app.o

# target to build an object file
src/app.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/osodio.dir/build.make CMakeFiles/osodio.dir/src/app.cpp.o
.PHONY : src/app.cpp.o

src/app.i: src/app.cpp.i
.PHONY : src/app.i

# target to preprocess a source file
src/app.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/osodio.dir/build.make CMakeFiles/osodio.dir/src/app.cpp.i
.PHONY : src/app.cpp.i

src/app.s: src/app.cpp.s
.PHONY : src/app.s

# target to generate assembly for a file
src/app.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/osodio.dir/build.make CMakeFiles/osodio.dir/src/app.cpp.s
.PHONY : src/app.cpp.s

src/core/event_loop.o: src/core/event_loop.cpp.o
.PHONY : src/core/event_loop.o

# target to build an object file
src/core/event_loop.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/osodio.dir/build.make CMakeFiles/osodio.dir/src/core/event_loop.cpp.o
.PHONY : src/core/event_loop.cpp.o

src/core/event_loop.i: src/core/event_loop.cpp.i
.PHONY : src/core/event_loop.i

# target to preprocess a source file
src/core/event_loop.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/osodio.dir/build.make CMakeFiles/osodio.dir/src/core/event_loop.cpp.i
.PHONY : src/core/event_loop.cpp.i

src/core/event_loop.s: src/core/event_loop.cpp.s
.PHONY : src/core/event_loop.s

# target to generate assembly for a file
src/core/event_loop.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/osodio.dir/build.make CMakeFiles/osodio.dir/src/core/event_loop.cpp.s
.PHONY : src/core/event_loop.cpp.s

src/core/tcp_server.o: src/core/tcp_server.cpp.o
.PHONY : src/core/tcp_server.o

# target to build an object file
src/core/tcp_server.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/osodio.dir/build.make CMakeFiles/osodio.dir/src/core/tcp_server.cpp.o
.PHONY : src/core/tcp_server.cpp.o

src/core/tcp_server.i: src/core/tcp_server.cpp.i
.PHONY : src/core/tcp_server.i

# target to preprocess a source file
src/core/tcp_server.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/osodio.dir/build.make CMakeFiles/osodio.dir/src/core/tcp_server.cpp.i
.PHONY : src/core/tcp_server.cpp.i

src/core/tcp_server.s: src/core/tcp_server.cpp.s
.PHONY : src/core/tcp_server.s

# target to generate assembly for a file
src/core/tcp_server.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/osodio.dir/build.make CMakeFiles/osodio.dir/src/core/tcp_server.cpp.s
.PHONY : src/core/tcp_server.cpp.s

src/http/http_connection.o: src/http/http_connection.cpp.o
.PHONY : src/http/http_connection.o

# target to build an object file
src/http/http_connection.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/osodio.dir/build.make CMakeFiles/osodio.dir/src/http/http_connection.cpp.o
.PHONY : src/http/http_connection.cpp.o

src/http/http_connection.i: src/http/http_connection.cpp.i
.PHONY : src/http/http_connection.i

# target to preprocess a source file
src/http/http_connection.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/osodio.dir/build.make CMakeFiles/osodio.dir/src/http/http_connection.cpp.i
.PHONY : src/http/http_connection.cpp.i

src/http/http_connection.s: src/http/http_connection.cpp.s
.PHONY : src/http/http_connection.s

# target to generate assembly for a file
src/http/http_connection.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/osodio.dir/build.make CMakeFiles/osodio.dir/src/http/http_connection.cpp.s
.PHONY : src/http/http_connection.cpp.s

src/http/http_parser.o: src/http/http_parser.cpp.o
.PHONY : src/http/http_parser.o

# target to build an object file
src/http/http_parser.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/osodio.dir/build.make CMakeFiles/osodio.dir/src/http/http_parser.cpp.o
.PHONY : src/http/http_parser.cpp.o

src/http/http_parser.i: src/http/http_parser.cpp.i
.PHONY : src/http/http_parser.i

# target to preprocess a source file
src/http/http_parser.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/osodio.dir/build.make CMakeFiles/osodio.dir/src/http/http_parser.cpp.i
.PHONY : src/http/http_parser.cpp.i

src/http/http_parser.s: src/http/http_parser.cpp.s
.PHONY : src/http/http_parser.s

# target to generate assembly for a file
src/http/http_parser.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/osodio.dir/build.make CMakeFiles/osodio.dir/src/http/http_parser.cpp.s
.PHONY : src/http/http_parser.cpp.s

src/router.o: src/router.cpp.o
.PHONY : src/router.o

# target to build an object file
src/router.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/osodio.dir/build.make CMakeFiles/osodio.dir/src/router.cpp.o
.PHONY : src/router.cpp.o

src/router.i: src/router.cpp.i
.PHONY : src/router.i

# target to preprocess a source file
src/router.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/osodio.dir/build.make CMakeFiles/osodio.dir/src/router.cpp.i
.PHONY : src/router.cpp.i

src/router.s: src/router.cpp.s
.PHONY : src/router.s

# target to generate assembly for a file
src/router.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/osodio.dir/build.make CMakeFiles/osodio.dir/src/router.cpp.s
.PHONY : src/router.cpp.s

third_party/llhttp/src/api.o: third_party/llhttp/src/api.c.o
.PHONY : third_party/llhttp/src/api.o

# target to build an object file
third_party/llhttp/src/api.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/llhttp.dir/build.make CMakeFiles/llhttp.dir/third_party/llhttp/src/api.c.o
.PHONY : third_party/llhttp/src/api.c.o

third_party/llhttp/src/api.i: third_party/llhttp/src/api.c.i
.PHONY : third_party/llhttp/src/api.i

# target to preprocess a source file
third_party/llhttp/src/api.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/llhttp.dir/build.make CMakeFiles/llhttp.dir/third_party/llhttp/src/api.c.i
.PHONY : third_party/llhttp/src/api.c.i

third_party/llhttp/src/api.s: third_party/llhttp/src/api.c.s
.PHONY : third_party/llhttp/src/api.s

# target to generate assembly for a file
third_party/llhttp/src/api.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/llhttp.dir/build.make CMakeFiles/llhttp.dir/third_party/llhttp/src/api.c.s
.PHONY : third_party/llhttp/src/api.c.s

third_party/llhttp/src/http.o: third_party/llhttp/src/http.c.o
.PHONY : third_party/llhttp/src/http.o

# target to build an object file
third_party/llhttp/src/http.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/llhttp.dir/build.make CMakeFiles/llhttp.dir/third_party/llhttp/src/http.c.o
.PHONY : third_party/llhttp/src/http.c.o

third_party/llhttp/src/http.i: third_party/llhttp/src/http.c.i
.PHONY : third_party/llhttp/src/http.i

# target to preprocess a source file
third_party/llhttp/src/http.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/llhttp.dir/build.make CMakeFiles/llhttp.dir/third_party/llhttp/src/http.c.i
.PHONY : third_party/llhttp/src/http.c.i

third_party/llhttp/src/http.s: third_party/llhttp/src/http.c.s
.PHONY : third_party/llhttp/src/http.s

# target to generate assembly for a file
third_party/llhttp/src/http.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/llhttp.dir/build.make CMakeFiles/llhttp.dir/third_party/llhttp/src/http.c.s
.PHONY : third_party/llhttp/src/http.c.s

third_party/llhttp/src/llhttp.o: third_party/llhttp/src/llhttp.c.o
.PHONY : third_party/llhttp/src/llhttp.o

# target to build an object file
third_party/llhttp/src/llhttp.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/llhttp.dir/build.make CMakeFiles/llhttp.dir/third_party/llhttp/src/llhttp.c.o
.PHONY : third_party/llhttp/src/llhttp.c.o

third_party/llhttp/src/llhttp.i: third_party/llhttp/src/llhttp.c.i
.PHONY : third_party/llhttp/src/llhttp.i

# target to preprocess a source file
third_party/llhttp/src/llhttp.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/llhttp.dir/build.make CMakeFiles/llhttp.dir/third_party/llhttp/src/llhttp.c.i
.PHONY : third_party/llhttp/src/llhttp.c.i

third_party/llhttp/src/llhttp.s: third_party/llhttp/src/llhttp.c.s
.PHONY : third_party/llhttp/src/llhttp.s

# target to generate assembly for a file
third_party/llhttp/src/llhttp.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/llhttp.dir/build.make CMakeFiles/llhttp.dir/third_party/llhttp/src/llhttp.c.s
.PHONY : third_party/llhttp/src/llhttp.c.s

third_party/simdjson.o: third_party/simdjson.cpp.o
.PHONY : third_party/simdjson.o

# target to build an object file
third_party/simdjson.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/simdjson.dir/build.make CMakeFiles/simdjson.dir/third_party/simdjson.cpp.o
.PHONY : third_party/simdjson.cpp.o

third_party/simdjson.i: third_party/simdjson.cpp.i
.PHONY : third_party/simdjson.i

# target to preprocess a source file
third_party/simdjson.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/simdjson.dir/build.make CMakeFiles/simdjson.dir/third_party/simdjson.cpp.i
.PHONY : third_party/simdjson.cpp.i

third_party/simdjson.s: third_party/simdjson.cpp.s
.PHONY : third_party/simdjson.s

# target to generate assembly for a file
third_party/simdjson.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/simdjson.dir/build.make CMakeFiles/simdjson.dir/third_party/simdjson.cpp.s
.PHONY : third_party/simdjson.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... distclean"
	@echo "... example"
	@echo "... llhttp"
	@echo "... osodio"
	@echo "... simdjson"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... src/app.o"
	@echo "... src/app.i"
	@echo "... src/app.s"
	@echo "... src/core/event_loop.o"
	@echo "... src/core/event_loop.i"
	@echo "... src/core/event_loop.s"
	@echo "... src/core/tcp_server.o"
	@echo "... src/core/tcp_server.i"
	@echo "... src/core/tcp_server.s"
	@echo "... src/http/http_connection.o"
	@echo "... src/http/http_connection.i"
	@echo "... src/http/http_connection.s"
	@echo "... src/http/http_parser.o"
	@echo "... src/http/http_parser.i"
	@echo "... src/http/http_parser.s"
	@echo "... src/router.o"
	@echo "... src/router.i"
	@echo "... src/router.s"
	@echo "... third_party/llhttp/src/api.o"
	@echo "... third_party/llhttp/src/api.i"
	@echo "... third_party/llhttp/src/api.s"
	@echo "... third_party/llhttp/src/http.o"
	@echo "... third_party/llhttp/src/http.i"
	@echo "... third_party/llhttp/src/http.s"
	@echo "... third_party/llhttp/src/llhttp.o"
	@echo "... third_party/llhttp/src/llhttp.i"
	@echo "... third_party/llhttp/src/llhttp.s"
	@echo "... third_party/simdjson.o"
	@echo "... third_party/simdjson.i"
	@echo "... third_party/simdjson.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

